INTRO = [
	"I'm going to hack",
	"I'm going to make",
	"My next DIY project is"
]

SOCIOPOLITICAL =  [
	'open-source',
	'free culture',
	'freegan',
	'vegan',
	'vegetarian',
	'free-range',
	'communist',
	'anarchist',
	'locally sourced',
	'artisanal',
	'ethical',
	'handcrafted',
	'microbrewed',
	'fair trade',
	'sex-positive',
	'kink-friendly',
	'queer-friendly',
	'tantric',
	'autonomous',
	'energy-neutral',
	'holistic',
	'vintage-inspired',
	'Soviet-inspired',
	'jailbroken',
	'hacktivist',
	'compostable',
	'all-natural',
	'hyperlocal',
	'crowdsourced',
    'single-origin',
	'sustainable',
	'military-inspired',
	'post-apocalyptic',
	'minimalist',
	'participatory',
    'futurist',
    'polyphasic',
    'no-waste',
    'upcycled',
    'non-binary',
    'human-powered',
    'hand-harvested',
    'cypherpunk',
    'irony-free',
    'anti-censorship',
    'urban'
]

PHYSICAL = [
'laser-cut',
'laser-etched',
'3D-printed',
'steampunk',
'hand-painted',
'cyberpunk',
'kinetic',
'clockwork',
'LED-lit',
'steam-driven',
'solar-powered',
'wind-powered',
'animated',
'leather',
'felt',
'analog',
'spraypainted',
'hand-tooled',
'acrylic',
'bioluminescent',
'ultralight',
'touch-screen',
'programmable',
'papercraft',
'vinyl',
'crocheted',
'knitted',
'cross-stitched',
'Arduino-powered',
'self-replicating',
'tweeting',
'Facebook-enabled',
'location-aware',
'nanoscale',
'bioluminescent',
'hemp',
'fungal',
'flat-screen',
'mobile',
'haptic',
'pressure-sensitive',
'remote-controlled',
'pocket-sized',
'collapsible',
'cat hair',
'screenprinted',
'greywater',
'brain-controlled'
]

ITEM = [
'robot',
'cyborg',
'3D printer',
('legwarmers', True),
('armwarmers', True),
('earrings', True),
('street art', True),
('soap', True),
('beer', True),
('moonshine', True),
('cupcakes', True),
'headband',
'burrito',
'beer cozy',
'sex toy',
'microcontroller',
'shrug',
'mp3 player',
'yoga mat',
'license plate frame',
'messenger bag',
'tote bag',
'turntable',
'art car',
'case mod',
'computer',
'typewriter',
'weather balloon',
'toilet seat',
'coffee maker',
'vehicle',
'glider',
'spacesuit',
'fedora',
'wedding dress',
'mandolin',
'tuxedo',
'evening gown',
'bicycle',
'tricycle',
'submarine',
'generator',
'sleeping bag',
'guitar',
'ukulele',
'bow tie',
'camera',
'spinning wheel',
'litterbox',
'wheelchair',
'architecture',
'mustache',
'graphic novel',
'ham radio',
'food truck',
'marijuana vaporizer',
'green roof',
'emoji',
'microcontroller',
'kombucha',
'operating system'
]

RESPONSES = [
"For your Etsy store?",
"I think I saw that on Boing Boing.",
"That will kick ass at Burning Man.",
"Right on, right on.",
"Aw, yeah.",
"Yeah, girl.",
"The hell is that?",
"And that is why you're single.",
"Is that legal?",
"For Mother's Day? Are you sure?",
"That's cool, bro.",
"Can I help?",
"You have been in San Francisco too long.",
"Did you get the kit for that at Maker Faire?",
"Whoa.",
"No shit.",
"Me too!",
"That'll show Washington.",
"Is it on Kickstarter yet?",
"I had the same idea last year!",
"Put a bird on it!"
]


